const data = [
    {
        "id": "1",
        "img": "young-nudy.webp",
        "title":"Will the New Young Nudy Album Live up to Expectations?",
        "description":"Dive deep into the Atlanta artist young Nudy",
        "author":"John MacAfee",
        "genre":"Rap, Hip Hop, Trap, Slime",
        "paragraph": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tortor felis, mattis sit amet urna eget, consequat pharetra velit. Mauris tincidunt nisi eget diam elementum, a mattis erat fringilla. Vivamus mollis varius mauris eu ornare. Donec eget aliquam nibh, quis fermentum augue. Praesent scelerisque metus eu tortor posuere condimentum. Curabitur augue sem, maximus a egestas at, pharetra imperdiet magna. Suspendisse faucibus ornare eros, vel ultricies massa aliquet eget. Sed fermentum vel ex quis finibus. Curabitur imperdiet, arcu non tempor vulputate, magna lacus sollicitudin dolor, non consectetur nunc mi dignissim quam. Maecenas commodo leo vitae commodo mattis. In hac habitasse platea dictumst. In rhoncus sem nec facilisis sollicitudin. Curabitur ut metus aliquam, dictum neque et, scelerisque enim. Aenean laoreet ante sed ornare faucibus. Vivamus quam nunc, placerat nec nisl et, imperdiet blandit lectus. Morbi et dolor ac libero faucibus aliquam.\n" +
            "\n" +
            "Proin convallis, dolor vel posuere hendrerit, erat massa condimentum lectus, a condimentum orci ipsum vitae erat. Aenean odio lectus, tincidunt non imperdiet quis, facilisis at augue. Quisque nec vulputate mi, et rutrum justo. Nulla facilisi. Nunc lacinia placerat eros quis egestas. Fusce arcu justo, bibendum at vehicula ac, aliquam eget diam. Cras sollicitudin urna quis viverra malesuada. Etiam luctus tortor eu elit ultrices tempus.\n" +
            "\n" +
            "Duis a finibus lorem, dignissim fringilla lorem. Proin eget congue turpis. Suspendisse scelerisque magna nec nulla rutrum lobortis. Cras quis tempor neque. Etiam eget odio ut diam fringilla mattis eget et est. Curabitur vel ex est. Praesent nulla orci, viverra vitae ligula a, eleifend pretium leo. Cras pulvinar mauris in metus maximus, eu mattis risus cursus. Sed viverra nibh sit amet nulla volutpat, ac consectetur tellus consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent malesuada mollis fringilla. Pellentesque ut pharetra urna. Quisque ut porta orci.\n" +
            "\n" +
            "Etiam facilisis eget est sed rhoncus. Ut ligula tortor, aliquam a porttitor et, facilisis sit amet nisi. Vivamus non cursus turpis. Pellentesque consequat ultricies nunc ac accumsan. Nam consequat nisi feugiat mi tincidunt dignissim eu eu mauris. Pellentesque eu eleifend eros. Morbi rutrum sit amet purus at ultrices. Pellentesque efficitur arcu sed dolor cursus, non sollicitudin eros dignissim. Integer tempus venenatis mauris, id auctor augue dapibus vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam augue orci, tincidunt id ullamcorper eu, viverra sit amet ipsum. Donec dapibus suscipit magna nec hendrerit. Pellentesque dignissim nulla a interdum vehicula.\n" +
            "\n" +
            "Quisque fermentum pellentesque purus eget imperdiet. Maecenas ligula libero, finibus in facilisis a, tempor non lectus. Sed dictum libero in luctus posuere. Vivamus posuere tristique nulla, nec facilisis ligula posuere a. Phasellus aliquet lacinia nibh vitae scelerisque. Nam varius risus quam, at aliquam ex malesuada in. Donec quis felis hendrerit, luctus risus facilisis, pretium tortor. Suspendisse id nunc at tortor finibus ornare. In dignissim nulla nibh, non aliquet mauris pellentesque sit amet. Vestibulum ultrices, nunc et interdum sollicitudin, metus turpis dapibus ante, non consequat metus mi vitae justo. Donec in mollis mi. Donec sit amet pellentesque enim, quis malesuada massa.\n" +
            "\n" +
            "Vestibulum eget odio at lectus dictum dictum id eget mi. Duis velit ligula, euismod vitae libero ut, accumsan facilisis sapien. Suspendisse rutrum posuere nisi. Sed at tempus magna. Aenean imperdiet turpis id bibendum pretium. Quisque nec finibus enim. Morbi facilisis, tortor ac ullamcorper aliquet, nulla ex accumsan elit, non sagittis neque purus vel elit.\n" +
            "\n" +
            "Proin nulla nisi, lacinia vel accumsan eu, varius vitae nisl. Nullam mi diam, dapibus consequat pretium eu, varius ut lorem. Integer cursus sagittis erat, eu sagittis ligula egestas tempor. Duis pretium id erat sed viverra. Nulla eleifend ipsum et felis maximus sagittis. Curabitur faucibus, arcu sed iaculis euismod, enim tellus pellentesque dolor, tempus sodales mauris est at nisi. Nunc lectus massa, commodo consectetur sollicitudin sed, dignissim ut enim. Sed sit amet aliquet nisi, ac pharetra augue. In eget tellus in dolor rhoncus pulvinar. Phasellus volutpat maximus elit eu tristique. Nunc vitae quam vehicula, scelerisque quam at, euismod nisi. Vivamus vel quam non tellus bibendum sollicitudin. Donec vel elit id ante sollicitudin faucibus sit amet vel dolor. Nam blandit varius odio, ut porttitor magna dapibus ac. Pellentesque hendrerit enim nisl, eu ornare dui malesuada sed. Vivamus consequat nulla ac leo aliquet, non efficitur est mollis."
    },
    {
        "id": "2",
        "img":"juniorh.jpg",
        "title":"How Junior H Saved My Life",
        "description":"Junior H creates music for people who want more in life",
        "author":"Carla Gomez",
        "genre":"Latin Trap, Sierreno, Corridos Tumbados",
        "paragraph": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tortor felis, mattis sit amet urna eget, consequat pharetra velit. Mauris tincidunt nisi eget diam elementum, a mattis erat fringilla. Vivamus mollis varius mauris eu ornare. Donec eget aliquam nibh, quis fermentum augue. Praesent scelerisque metus eu tortor posuere condimentum. Curabitur augue sem, maximus a egestas at, pharetra imperdiet magna. Suspendisse faucibus ornare eros, vel ultricies massa aliquet eget. Sed fermentum vel ex quis finibus. Curabitur imperdiet, arcu non tempor vulputate, magna lacus sollicitudin dolor, non consectetur nunc mi dignissim quam. Maecenas commodo leo vitae commodo mattis. In hac habitasse platea dictumst. In rhoncus sem nec facilisis sollicitudin. Curabitur ut metus aliquam, dictum neque et, scelerisque enim. Aenean laoreet ante sed ornare faucibus. Vivamus quam nunc, placerat nec nisl et, imperdiet blandit lectus. Morbi et dolor ac libero faucibus aliquam.\n" +
            "\n" +
            "Proin convallis, dolor vel posuere hendrerit, erat massa condimentum lectus, a condimentum orci ipsum vitae erat. Aenean odio lectus, tincidunt non imperdiet quis, facilisis at augue. Quisque nec vulputate mi, et rutrum justo. Nulla facilisi. Nunc lacinia placerat eros quis egestas. Fusce arcu justo, bibendum at vehicula ac, aliquam eget diam. Cras sollicitudin urna quis viverra malesuada. Etiam luctus tortor eu elit ultrices tempus.\n" +
            "\n" +
            "Duis a finibus lorem, dignissim fringilla lorem. Proin eget congue turpis. Suspendisse scelerisque magna nec nulla rutrum lobortis. Cras quis tempor neque. Etiam eget odio ut diam fringilla mattis eget et est. Curabitur vel ex est. Praesent nulla orci, viverra vitae ligula a, eleifend pretium leo. Cras pulvinar mauris in metus maximus, eu mattis risus cursus. Sed viverra nibh sit amet nulla volutpat, ac consectetur tellus consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent malesuada mollis fringilla. Pellentesque ut pharetra urna. Quisque ut porta orci.\n" +
            "\n" +
            "Etiam facilisis eget est sed rhoncus. Ut ligula tortor, aliquam a porttitor et, facilisis sit amet nisi. Vivamus non cursus turpis. Pellentesque consequat ultricies nunc ac accumsan. Nam consequat nisi feugiat mi tincidunt dignissim eu eu mauris. Pellentesque eu eleifend eros. Morbi rutrum sit amet purus at ultrices. Pellentesque efficitur arcu sed dolor cursus, non sollicitudin eros dignissim. Integer tempus venenatis mauris, id auctor augue dapibus vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam augue orci, tincidunt id ullamcorper eu, viverra sit amet ipsum. Donec dapibus suscipit magna nec hendrerit. Pellentesque dignissim nulla a interdum vehicula.\n" +
            "\n" +
            "Quisque fermentum pellentesque purus eget imperdiet. Maecenas ligula libero, finibus in facilisis a, tempor non lectus. Sed dictum libero in luctus posuere. Vivamus posuere tristique nulla, nec facilisis ligula posuere a. Phasellus aliquet lacinia nibh vitae scelerisque. Nam varius risus quam, at aliquam ex malesuada in. Donec quis felis hendrerit, luctus risus facilisis, pretium tortor. Suspendisse id nunc at tortor finibus ornare. In dignissim nulla nibh, non aliquet mauris pellentesque sit amet. Vestibulum ultrices, nunc et interdum sollicitudin, metus turpis dapibus ante, non consequat metus mi vitae justo. Donec in mollis mi. Donec sit amet pellentesque enim, quis malesuada massa.\n" +
            "\n" +
            "Vestibulum eget odio at lectus dictum dictum id eget mi. Duis velit ligula, euismod vitae libero ut, accumsan facilisis sapien. Suspendisse rutrum posuere nisi. Sed at tempus magna. Aenean imperdiet turpis id bibendum pretium. Quisque nec finibus enim. Morbi facilisis, tortor ac ullamcorper aliquet, nulla ex accumsan elit, non sagittis neque purus vel elit.\n" +
            "\n" +
            "Proin nulla nisi, lacinia vel accumsan eu, varius vitae nisl. Nullam mi diam, dapibus consequat pretium eu, varius ut lorem. Integer cursus sagittis erat, eu sagittis ligula egestas tempor. Duis pretium id erat sed viverra. Nulla eleifend ipsum et felis maximus sagittis. Curabitur faucibus, arcu sed iaculis euismod, enim tellus pellentesque dolor, tempus sodales mauris est at nisi. Nunc lectus massa, commodo consectetur sollicitudin sed, dignissim ut enim. Sed sit amet aliquet nisi, ac pharetra augue. In eget tellus in dolor rhoncus pulvinar. Phasellus volutpat maximus elit eu tristique. Nunc vitae quam vehicula, scelerisque quam at, euismod nisi. Vivamus vel quam non tellus bibendum sollicitudin. Donec vel elit id ante sollicitudin faucibus sit amet vel dolor. Nam blandit varius odio, ut porttitor magna dapibus ac. Pellentesque hendrerit enim nisl, eu ornare dui malesuada sed. Vivamus consequat nulla ac leo aliquet, non efficitur est mollis."
    },
    {
        "id": "3",
        "img":"src/assets/images/Helena_Hauff.jpg",
        "title":"Helena Hauff is the New New",
        "description":"Contemplative and destructive, Helena Hauff is here and ready",
        "author":"James Holland",
        "genre":"Techno, EDM, Melodic",
        "paragraph": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tortor felis, mattis sit amet urna eget, consequat pharetra velit. Mauris tincidunt nisi eget diam elementum, a mattis erat fringilla. Vivamus mollis varius mauris eu ornare. Donec eget aliquam nibh, quis fermentum augue. Praesent scelerisque metus eu tortor posuere condimentum. Curabitur augue sem, maximus a egestas at, pharetra imperdiet magna. Suspendisse faucibus ornare eros, vel ultricies massa aliquet eget. Sed fermentum vel ex quis finibus. Curabitur imperdiet, arcu non tempor vulputate, magna lacus sollicitudin dolor, non consectetur nunc mi dignissim quam. Maecenas commodo leo vitae commodo mattis. In hac habitasse platea dictumst. In rhoncus sem nec facilisis sollicitudin. Curabitur ut metus aliquam, dictum neque et, scelerisque enim. Aenean laoreet ante sed ornare faucibus. Vivamus quam nunc, placerat nec nisl et, imperdiet blandit lectus. Morbi et dolor ac libero faucibus aliquam.\n" +
            "\n" +
            "Proin convallis, dolor vel posuere hendrerit, erat massa condimentum lectus, a condimentum orci ipsum vitae erat. Aenean odio lectus, tincidunt non imperdiet quis, facilisis at augue. Quisque nec vulputate mi, et rutrum justo. Nulla facilisi. Nunc lacinia placerat eros quis egestas. Fusce arcu justo, bibendum at vehicula ac, aliquam eget diam. Cras sollicitudin urna quis viverra malesuada. Etiam luctus tortor eu elit ultrices tempus.\n" +
            "\n" +
            "Duis a finibus lorem, dignissim fringilla lorem. Proin eget congue turpis. Suspendisse scelerisque magna nec nulla rutrum lobortis. Cras quis tempor neque. Etiam eget odio ut diam fringilla mattis eget et est. Curabitur vel ex est. Praesent nulla orci, viverra vitae ligula a, eleifend pretium leo. Cras pulvinar mauris in metus maximus, eu mattis risus cursus. Sed viverra nibh sit amet nulla volutpat, ac consectetur tellus consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent malesuada mollis fringilla. Pellentesque ut pharetra urna. Quisque ut porta orci.\n" +
            "\n" +
            "Etiam facilisis eget est sed rhoncus. Ut ligula tortor, aliquam a porttitor et, facilisis sit amet nisi. Vivamus non cursus turpis. Pellentesque consequat ultricies nunc ac accumsan. Nam consequat nisi feugiat mi tincidunt dignissim eu eu mauris. Pellentesque eu eleifend eros. Morbi rutrum sit amet purus at ultrices. Pellentesque efficitur arcu sed dolor cursus, non sollicitudin eros dignissim. Integer tempus venenatis mauris, id auctor augue dapibus vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam augue orci, tincidunt id ullamcorper eu, viverra sit amet ipsum. Donec dapibus suscipit magna nec hendrerit. Pellentesque dignissim nulla a interdum vehicula.\n" +
            "\n" +
            "Quisque fermentum pellentesque purus eget imperdiet. Maecenas ligula libero, finibus in facilisis a, tempor non lectus. Sed dictum libero in luctus posuere. Vivamus posuere tristique nulla, nec facilisis ligula posuere a. Phasellus aliquet lacinia nibh vitae scelerisque. Nam varius risus quam, at aliquam ex malesuada in. Donec quis felis hendrerit, luctus risus facilisis, pretium tortor. Suspendisse id nunc at tortor finibus ornare. In dignissim nulla nibh, non aliquet mauris pellentesque sit amet. Vestibulum ultrices, nunc et interdum sollicitudin, metus turpis dapibus ante, non consequat metus mi vitae justo. Donec in mollis mi. Donec sit amet pellentesque enim, quis malesuada massa.\n" +
            "\n" +
            "Vestibulum eget odio at lectus dictum dictum id eget mi. Duis velit ligula, euismod vitae libero ut, accumsan facilisis sapien. Suspendisse rutrum posuere nisi. Sed at tempus magna. Aenean imperdiet turpis id bibendum pretium. Quisque nec finibus enim. Morbi facilisis, tortor ac ullamcorper aliquet, nulla ex accumsan elit, non sagittis neque purus vel elit.\n" +
            "\n" +
            "Proin nulla nisi, lacinia vel accumsan eu, varius vitae nisl. Nullam mi diam, dapibus consequat pretium eu, varius ut lorem. Integer cursus sagittis erat, eu sagittis ligula egestas tempor. Duis pretium id erat sed viverra. Nulla eleifend ipsum et felis maximus sagittis. Curabitur faucibus, arcu sed iaculis euismod, enim tellus pellentesque dolor, tempus sodales mauris est at nisi. Nunc lectus massa, commodo consectetur sollicitudin sed, dignissim ut enim. Sed sit amet aliquet nisi, ac pharetra augue. In eget tellus in dolor rhoncus pulvinar. Phasellus volutpat maximus elit eu tristique. Nunc vitae quam vehicula, scelerisque quam at, euismod nisi. Vivamus vel quam non tellus bibendum sollicitudin. Donec vel elit id ante sollicitudin faucibus sit amet vel dolor. Nam blandit varius odio, ut porttitor magna dapibus ac. Pellentesque hendrerit enim nisl, eu ornare dui malesuada sed. Vivamus consequat nulla ac leo aliquet, non efficitur est mollis."
    },
    {
        "id": "4",
        "img":"Hiatus_Kaiyote.jpg",
        "title":"Hiatus Kaiyote Saves Australia Once Again",
        "description":"Hiatus Kaiyote releases their most eagerly awaited album",
        "author":"Jojo Marx",
        "genre":"Jazz, Soul, R&B, Neo Soul",
        "paragraph": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tortor felis, mattis sit amet urna eget, consequat pharetra velit. Mauris tincidunt nisi eget diam elementum, a mattis erat fringilla. Vivamus mollis varius mauris eu ornare. Donec eget aliquam nibh, quis fermentum augue. Praesent scelerisque metus eu tortor posuere condimentum. Curabitur augue sem, maximus a egestas at, pharetra imperdiet magna. Suspendisse faucibus ornare eros, vel ultricies massa aliquet eget. Sed fermentum vel ex quis finibus. Curabitur imperdiet, arcu non tempor vulputate, magna lacus sollicitudin dolor, non consectetur nunc mi dignissim quam. Maecenas commodo leo vitae commodo mattis. In hac habitasse platea dictumst. In rhoncus sem nec facilisis sollicitudin. Curabitur ut metus aliquam, dictum neque et, scelerisque enim. Aenean laoreet ante sed ornare faucibus. Vivamus quam nunc, placerat nec nisl et, imperdiet blandit lectus. Morbi et dolor ac libero faucibus aliquam.\n" +
            "\n" +
            "Proin convallis, dolor vel posuere hendrerit, erat massa condimentum lectus, a condimentum orci ipsum vitae erat. Aenean odio lectus, tincidunt non imperdiet quis, facilisis at augue. Quisque nec vulputate mi, et rutrum justo. Nulla facilisi. Nunc lacinia placerat eros quis egestas. Fusce arcu justo, bibendum at vehicula ac, aliquam eget diam. Cras sollicitudin urna quis viverra malesuada. Etiam luctus tortor eu elit ultrices tempus.\n" +
            "\n" +
            "Duis a finibus lorem, dignissim fringilla lorem. Proin eget congue turpis. Suspendisse scelerisque magna nec nulla rutrum lobortis. Cras quis tempor neque. Etiam eget odio ut diam fringilla mattis eget et est. Curabitur vel ex est. Praesent nulla orci, viverra vitae ligula a, eleifend pretium leo. Cras pulvinar mauris in metus maximus, eu mattis risus cursus. Sed viverra nibh sit amet nulla volutpat, ac consectetur tellus consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent malesuada mollis fringilla. Pellentesque ut pharetra urna. Quisque ut porta orci.\n" +
            "\n" +
            "Etiam facilisis eget est sed rhoncus. Ut ligula tortor, aliquam a porttitor et, facilisis sit amet nisi. Vivamus non cursus turpis. Pellentesque consequat ultricies nunc ac accumsan. Nam consequat nisi feugiat mi tincidunt dignissim eu eu mauris. Pellentesque eu eleifend eros. Morbi rutrum sit amet purus at ultrices. Pellentesque efficitur arcu sed dolor cursus, non sollicitudin eros dignissim. Integer tempus venenatis mauris, id auctor augue dapibus vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam augue orci, tincidunt id ullamcorper eu, viverra sit amet ipsum. Donec dapibus suscipit magna nec hendrerit. Pellentesque dignissim nulla a interdum vehicula.\n" +
            "\n" +
            "Quisque fermentum pellentesque purus eget imperdiet. Maecenas ligula libero, finibus in facilisis a, tempor non lectus. Sed dictum libero in luctus posuere. Vivamus posuere tristique nulla, nec facilisis ligula posuere a. Phasellus aliquet lacinia nibh vitae scelerisque. Nam varius risus quam, at aliquam ex malesuada in. Donec quis felis hendrerit, luctus risus facilisis, pretium tortor. Suspendisse id nunc at tortor finibus ornare. In dignissim nulla nibh, non aliquet mauris pellentesque sit amet. Vestibulum ultrices, nunc et interdum sollicitudin, metus turpis dapibus ante, non consequat metus mi vitae justo. Donec in mollis mi. Donec sit amet pellentesque enim, quis malesuada massa.\n" +
            "\n" +
            "Vestibulum eget odio at lectus dictum dictum id eget mi. Duis velit ligula, euismod vitae libero ut, accumsan facilisis sapien. Suspendisse rutrum posuere nisi. Sed at tempus magna. Aenean imperdiet turpis id bibendum pretium. Quisque nec finibus enim. Morbi facilisis, tortor ac ullamcorper aliquet, nulla ex accumsan elit, non sagittis neque purus vel elit.\n" +
            "\n" +
            "Proin nulla nisi, lacinia vel accumsan eu, varius vitae nisl. Nullam mi diam, dapibus consequat pretium eu, varius ut lorem. Integer cursus sagittis erat, eu sagittis ligula egestas tempor. Duis pretium id erat sed viverra. Nulla eleifend ipsum et felis maximus sagittis. Curabitur faucibus, arcu sed iaculis euismod, enim tellus pellentesque dolor, tempus sodales mauris est at nisi. Nunc lectus massa, commodo consectetur sollicitudin sed, dignissim ut enim. Sed sit amet aliquet nisi, ac pharetra augue. In eget tellus in dolor rhoncus pulvinar. Phasellus volutpat maximus elit eu tristique. Nunc vitae quam vehicula, scelerisque quam at, euismod nisi. Vivamus vel quam non tellus bibendum sollicitudin. Donec vel elit id ante sollicitudin faucibus sit amet vel dolor. Nam blandit varius odio, ut porttitor magna dapibus ac. Pellentesque hendrerit enim nisl, eu ornare dui malesuada sed. Vivamus consequat nulla ac leo aliquet, non efficitur est mollis."
    }
]
export default { data }